# Generated by Django 5.2 on 2025-06-06 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exits.'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989\\d{9}', 'Enter a valid mobile number like 989XXXXXXXXX ')], verbose_name='mobile number'),
        ),
    ]
