# Generated by Django 5.2 on 2025-06-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.Unselect this instead of deleting acounts', verbose_name='active'),
        ),
    ]
